### ISSUE TITLE
Trying to signin with a second account will give "unable to find public key" error

### ISSUE THREAD

**Issue by braydonf** [Storj/bridge-gui-vue#13]
Was able to reproduce the "unable to find public key" error. And it's when a "second" user is being logged in after another user has logged in before. It's not specifically related to "new users" or the way a user is registered. There is a request to `DELETE /keys/<pubkey`, however this will fail as the key is used by another user, it gives a status code `404`, after this point it fails.

**Work around**
Clear your local storage in your browser

**Solution**
Store keys in localstorage keyed by email so as to not try and delete a key to which does not belong to the user

**Comment by dylanlott** [comment]
Fixed per #23  - Closing.
