### ISSUE TITLE
Referral system does not provide a valid link for share

### ISSUE THREAD

**Issue by luzemario** [Storj/bridge-gui-vue#15]
Hi guys, the referral web page generates a referral link to share within one's social networks. But the link generated for me is not a valid link. I think there is a issue with the referral code. Please see the image below on the right field "share your link":

![2017-10-05-080302_1280x800_scrot](https://user-images.githubusercontent.com/6605180/31234505-6a4c8aac-a9c5-11e7-9d86-bc499d5cd9e2.png)

This was seen on Firefox ESR 52.3.0 (64-bit). Please check the code.

**Comment by pgerbes1** [comment]
Hi @luzemario thank you for bringing this to our attention. Are you able to also post the error message you receive?

**Comment by luzemario** [comment]
There is no error message from what I could notice. It appears to be that the generated text is not a URL, or is incomplete.

**Comment by pgerbes1** [comment]
Ok got it. Thanks!

**Comment by navillasa** [comment]
Closed with https://github.com/Storj/bridge-gui-vue/pull/32
