### ISSUE TITLE
Indicate timeframe for BTC credits to post to account

### ISSUE THREAD

**Issue by barbaraliau** [Storj/bridge-gui-vue#3]
This is indicated on bitpay page, but it would be good to also indicate it on our page e.g. as a tooltip or an expandable `?`

**Comment by dylanlott** [comment]
This is still an enhancement I'd like to see for Coinpayments credits as well

**Comment by dylanlott** [comment]
Closing - we have language in the modal that notifies the user of time for crypto payments to be confirmed.
