### ISSUE TITLE
Can't log in

### ISSUE THREAD

**Issue by stobias123** [Storj/bridge-gui-vue#6]
Trying to log in after bringing up the environment and I get an error "Storj is not defined". 

I think the problem is that the link to `storj.es6.js` isn't relative - it built with the full path including localhost (which isn't available when building from SDK).

line in question at  https://192.168.x.x/login
```<script src=//localhost:3001/static/vendor/storj.es6.js>```

**Comment by barbaraliau** [comment]
Cool. Did changing the path work for you then? I can check it out when I get back to my computer.

**Comment by stobias123** [comment]
I added the below to the index.html page and it worked. I'm not sure where it was being generated so I just manually added it.

```<script type="text/javascript" src="https://js.stripe.com/v2/"></script>
+    <script src="/static/vendor/storj.es6.js"></script>
```

Only problem is that the post action for login still goes to api.storj.io - not sure where to change that config setting - maybe just in the es6 file.

**Comment by barbaraliau** [comment]
https://github.com/Storj/bridge-gui-vue/blob/master/config/index.js

You'll need to set the environment. I'll have to change the default to go to dev env instead of prod env.

**Comment by dylanlott** [comment]
Closing since opener has not replied and the issue seems to have been addressed.
